# 예외 처리기 (Exception Handler)

일번적으로 예외 처리기는 특정 예외의 처리를 위해 사용된다. 예외 처리 구문은 처리 방법을 알고 있는 예외를 제외한 모든 예외를 필터링하고 처리할 수 있다. 
다른 예외는 특정 예외를 처리하도록 작성된 다른 예외 처리기에 전달된다. C++ 언어에서 예외 처리기를 구현하기 위해서는 **try**, **catch**, **throw** 키워드를 사용한다. 

**try** 블록은 예외를 발생시킬 수도 있는 하나 이상의 문장을 포함하기 위해 사용된다. 
**throw** 키워드는 예외 조건이 발생하였음올 나타낸다. **throw** 표현의 피연산자로는 모든 유형의 객체를 사용할 수 있다. 
일반적으로 이 객체는 에러에 관한 정보를 전달하는데 사용된다. 대부분 **std::exception** 클래스 또는 포준 라이브러리에 정의된 파생 클래스 중 하나를 사용하는 것이 좋다. 

## 예외 처리의 기본 형식

C++에서의 예외 처리는 **try-throw-catch**의 구조로 작성되며, 일반적으로 다음의 형태를 띄고 있다.
```c++
try { // 예외가 발생할 수 있는 코드를 삽입하는 곳

	  예외가 발견되면{
			throw x; // 예외의 발생을 알림, x는 예외 값
		}

	  예외가 발견되면{
			throw y; // 예외의 발생을 알림, y는 예외 값
		}
	}
	catch (처리할 예외 파라미터 선언) {
		예외 처리문
	}
	catch (처리할 예외 파라미터 선언) {
		예외 처리문
	}
```

+ ## try {}
  예외 발생을 탐지하는 코드를 작성하고 catch(){}와 연결하여 이러한 예외를 처리하도록 한다. try{} 내에는 여러 개의 catch(){}를 만들 수 있으며
  예외가 탐지되면 throw 문을 실행하여 예외의 발생을 알린다.
  
+ ## throw 문
  try{} 내에서 실행되는 문으로, 현재 실행중인 프로그램의 예외 발생을 알린다. throw는 예외 발생 시 특정한 **예외 값**을 가지며 예외 발생의 알림은 **'예외 값을 던지다' **라고 표현된다.
  ```c++
  throw 10;            // 정수형 타입의 예외 값 10을 던짐
  throw "empty stack"; // char* 타입의 문자열 예외를 던짐
  ```
  
  
  throw 문이 실행되면
  catch(){}로 넘어가 해당 예외를 처리하기 시작하므로 throw 문 다음에 다른 try{}가 있을 경우 이는 실행되지 않는다.
  throw에서는 정수, 문자, 실수, 문자열, 객체 등 다양한 타입의 예외를 던질 수 있다. 또한, tyr{}내에는 여러 개의 throw가 존재할 수 있다.
  
+ ## catch(처리할 예외 파라미터){}

  throw에서 던진 예외는 연결된 catch(){}에서 처리되며, 이 때 catch(){}에는 예외 값을 전달받을 수 있는 **예외 파라미터**가 작성되어 있어야 한다. 
  만약 **throw에서 던진 예외 값을 받을 수 있는 catch(){}가 없을 경우 프로그램은 종료된다. 또한, 예외 파라미터는 오직 하나만 선언할 수 있다.**
  예외 파라미터는 함수의 파라미터와 같이 '예외 타입'과 '매개 변수'로 이루어져 있으며 throw에서 던진 예외 값과 일치하는 타입의 예외 파라미터를 가진 catch(){}가 실행된다. 
  
던져진 예외 값은 '타입'으로 구분되며 하나의 catch(){}는 하나의 예외 타입만을 처리한다. 다음은 여러가지 타입의 예외를 던지는 throw 문장과 해당 타입의 예외를 처리하는
catch(){}의 예이다.
+ int 타입의 예외 처리
```c++
try {
  throw 3; // int 타입의 예외 값 3을 던짐
  ``
  }
catch( int x ) { // x에 3을 전달받음
``
  }
```
+ double 타입의 예외 처리
```c++
try {
  throw 3.5; // double 타입의 예외 값 3.5를 던짐
  ``
  }
catch( double x ) { // x에 3.5를 전달받음
  cout << "실수 예외 값 : " << x << endl;
  }
```

+ 문자열 타입의 예외 처리
```c++
try {
  throw "배열 인덱스 범위 초과"; // char* 타입의 예외fmf 던짐
  ``
  }
catch( const char* s ) { // const char* 타입의 예외 처리, throw에서 던진 문자열을 s에 저장
  cout << x << endl;     // "배열 인덱스 범위 초과" 문자열 출력
  }
```

## try-throw-catch의 예외 처리 과정

다음은 정수를 0 또는 음수로 나누는 예외를 탐지하고 처리하는 코드이다. 
```c++
int main(int argc, const char* argv[]) {
	
	int n, sum, average;
	while (true) {
		cout << "합을 입력" << endl;
		cin >> sum;
		cout << "인원수를 입력" << endl;
		cin >> n;
		try {
			if (n <= 0)            // 오류 탐지 코드
				throw n;           // 예외 값을 던짐
			else
				average = sum / n; // 오류가 아닐 경우 정상 연산
		}
		catch (int x) {            // 오류가 발생했을 경우 예외 값을 전달받고 실행
			cout << "예외 발생 : " << n << "으로 나눌 수 없음" << endl;
			average = 0;
			cout << endl;
			break;                 // 반복문 종료
		}
		cout << "평균 = " << average << endl << endl;
	}

	return 0;
}
```
실행 결과
```c++
합을 입력
24
인원수를 입력
5
평균 = 4

합을 입력
26
인원수를 입력
0
예외 발생 : 0으로 나눌 수 없음
```

오류의 탐지는 정수를 나누는 n의 값을 입력할 때 이루어진다. 위의 예시에서는 조건문을 이용해 오류를 탐지하며 n이 0 또는 음수가 아닐 경우 else 문 아래로 코드를 정상적으로 실행하지만,
조건문이 참일 경우 throw문에 의해 n의 값이 catch로 던져지고 프로그램의 실행은 catch로 건너띄어진다. 던져진 n의 값과 일치하는 타입의 예외 파라미터를 가진 catch가 존재하므로,
해당 catch 내부의 문장이 실행된다.

만약 예외 값의 타입과 일치하는 예외 파라미터를 가진 catch가 없을 경우, 프로그램은 비정상적으로 종료된다.
